# Server configuration
server:
  port: 8085

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false


